DROP DATABASE if exists db_plp;

CREATE DATABASE db_plp;
USE db_plp;

CREATE TABLE tbl_player
(
	openid VARCHAR(28) NOT NULL PRIMARY KEY,
	data BLOB NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT="用户表";